# Generated by Django 5.2.6 on 2025-09-16 12:10

import theatre.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=theatre.utils.play_image_file_path
            ),
        ),
    ]
