# Generated by Django 5.2.6 on 2025-09-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_play_image"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="performance",
            constraint=models.UniqueConstraint(
                fields=("play", "theatre_hall", "show_time"),
                name="uniq_performance_hall_time",
            ),
        ),
    ]
